import { LanguageProvider } from "./providers/LanguageProvider"
import Navbar from "./components/Navbar"
import "./globals.css"

export const metadata = {
  title: 'Jose Hinojosa - Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <LanguageProvider>
          <Navbar />
          {children}
        </LanguageProvider>
      </body>
    </html>
  )
}
